### ISSUE TITLE
Searching for experiment note of analyze Nginx or other with BOPC

### ISSUE THREAD

**Issue by yingchuan-d** [HexHive/BOPC#12]
I'm going nuts! :(  Who can help me with an experiment note or something like it? Just need the original one, or it's better if you can add some explanation or the result.

**Comment by Lightninghkm** [comment]
Hi Yingchuan (correct me if this is not your name :)),

Sorry to hear that you have trouble running BOPC, I'm glad to be here to help you with these issues.

First, make sure you run ```sh setup.sh``` before running analysis, note that you should keep the version of all dependencies as specified in the ```setup.sh``` script, otherwise you may run into dependency issues. Moreover, if the being installed packages are conflict with the packages already installed in your OS, simply substitute ```apt-get``` with ```aptitude``` and use ```—user``` option with ```pip install```. Make sure you delete all ```.pyc``` file in the “source” directory before running ```sh setup.sh```.

The folder ```evaluation``` contains the original dataset of BOPC’s evaluation. Note that 32 GB physical memory is recommended (not required) for testing some of the target binaries. If BOPC runs into out-of-memory issues, it should show some unexpected behavior and weird errors, so it would be the time to configure more memory of your OS when you encounter this situation. 

The folder ```source``` contains the source code of BOPC.

The folder ```payload``` contains the SPL payload – attack format defined by user. In short, SPL payload is fed to BOPC as the input to let BOPC know what kind of exploitation is going to be synthesized.

Let me give you some instructions about running BOPC on a specific example:

Let’s say we want to search for a feasible ```infinite loop``` by performing a data-only attack using BOPC towards target binary ```nginx```. Basically if we successfully arrange an infinite-loop within the program’s normal control flow by performing data-only attack, that at least means an DoS attack and should not be mitigated by CFI.

 So, the first step we need to do is to create an abstraction file for nginx by the following command:

```
 ./source/BOPC.py -dd --binary evaluation/nginx1 --abstraction saveonly
```

After this, you should get an abstraction file named “nginx1.abs” in the directory /evaluation.

 Then we need to run the following command to trigger the searching steps of BOPC:

```
./source/BOPC.py -dd --binary evaluation/nginx1 --source payloads/infloop.spl --abstraction load --entry -1 --format gdb
```
 
Note that ```–entry -1``` means setting the starting of the target binary as entry point. After waiting a bit, we should get a solution file named ```nginx1-infloop_xxxxxxxx.gdb``` in directory ```evaluation```, which is the gdb-script version of BOPC’s output. You can load the target binary into gdb and run this scripts to evaluate the result without building any dependencies of the target binary. In some of the cases, BOPC indeed gives us 0 solution simply because that attacker can’t generate the SPL payload defined attack toward this binary. However, since the running time of BOPC is non-deterministic, you should wait for some time to get the results.

When using BOPC, you actually don’t need to run the target binary, since it relies on concolic execution. Thus, just use those pre-compiled binaries or choose the compiled binaries that are of your interest

Good luck!

Kaiming.

**Comment by yingchuan-d** [comment]
THANKS，Kaiming!!! Your answer really help me a lot. Before, I can't run BOPC successfully because of the version of an dependency. Now, I change the version and then succeed.
